/*! \file
 *
 * \brief Package version information.
 *
 * \warning Auto-generated by Rules.mk on 2020.06.15 14:01:46
 *
 * \pkgfile{version.h}
 */

#ifndef _VERSION_H
#define _VERSION_H

/*! package name */
#define PKG_NAME "aetherinstinct"

/*! package dotted version */
#define PKG_VERSION "0.5.0"

/*! package build date */
#define PKG_TIMESTAMP "2020.06.15 14:01:46"

/*! package extended creation date */
#define PKG_DATE "2019"

/*! package full name */
#define PKG_FULL_NAME "aetherinstinct-0.5.0"

/*! package author(s) */
#define PKG_AUTHORS "Robin Knight"

/*! package owner(s) */
#define PKG_OWNERS "Aether Instinct LLC"

/*! package legal disclaimer */
#define PKG_DISCLAIMER "See the LICENSE file for any copyright and licensing information."

#endif // _VERSION_H

